### ISSUE TITLE
Should regressing/improving tests be re-run?

### ISSUE THREAD

**Issue by timholy** [JuliaCI/BenchmarkTools.jl#10]
Given the large number of tests, there is still a fair amount of noise in the reports. It would seem that one way to reduce the noise would be to follow up on apparent regressions/improvements with a re-running of those tests. I haven't looked into the infrastructure at all to see how easy this would be, but if both builds are still available I'm wondering whether this would be fairly straightforward?

**Comment by jrevels** [comment]
moved to JuliaCI/Nanosoldier.jl#4
