### ISSUE TITLE
Add StopWatch? See suggested implementation.

### ISSUE THREAD

**Issue by dataPulverizer** [JuliaCI/BenchmarkTools.jl#100]
Add simple stopwatch, see below for basic suggested implementation:

```
mutable struct StopWatch
	t1::Float64
	t2::Float64
	StopWatch() = new(NaN, NaN)
end

function start!(sw::StopWatch)::Nothing
  sw.t1 = time()
  Nothing()
end

function stop!(sw::StopWatch)::Nothing
	sw.t2 = time()
	Nothing()
end

function reset!(sw::StopWatch)::Nothing
	sw.t2 = sw.t1 = NaN
  Nothing()
end

peek(sw::StopWatch) = isnan(sw.t1) ? throw("StopWatch ($sw) has not been started.") : isnan(sw.t2) ? time() - sw.t1 : sw.t2 - sw.t1
# duration(sw::StopWatch) = sw.t2 - sw.t1

# Demo
cl = StopWatch() # peek(cl) # error
start!(cl); sleep(2); peek(cl)
sleep(1); stop!(cl); peek(cl); reset!(cl)
```
Because sometimes you just want a stop watch.

**Comment by ararslan** [comment]
If I understand correctly this is like `tic` and `toq` from Julia < 0.7, right?

**Comment by dataPulverizer** [comment]
To be honest, I didn't know about `tic` and `toc` but I get the general idea yes.

**Comment by gdalle** [comment]
Here is why these were deprecated: https://github.com/JuliaLang/julia/issues/17046

Basically a stopwatch like this encourages people to benchmark in the global scope, which is a bad idea. I don't think it belongs in BenchmarkTools (but maybe it already exists elsewhere?)
