### ISSUE TITLE
Tag a release please!

### ISSUE THREAD

**Issue by peterahrens** [JuliaCI/BenchmarkTools.jl#131]
Please tag a release of BenchmarkSuites that contains the recent updates to the show infrastructure on Julia v1.0.0.

**Comment by ararslan** [comment]
I tagged v0.4.2 but Attobot hasn't made a PR to METADATA yet. Not sure what the deal with that is.

**Comment by ararslan** [comment]
Simon retriggered it. https://github.com/JuliaLang/METADATA.jl/pull/20821

**Comment by peterahrens** [comment]
Thanks @ararslan!
