### ISSUE TITLE
First example in README is invalid

### ISSUE THREAD

**Issue by robsmith11** [JuliaCI/BenchmarkTools.jl#134]
The first example in the README `@btime sin(1)` (no longer?) measures anything meaningful because the expression is constant-folded, which makes it a rather poor demonstration of how to use BenchmarkTools.

A better example should be used and perhaps a section could be added on avoiding situations like this.

See also
https://discourse.julialang.org/t/benchmarktools-with-simple-fast-running-function/21049/2

**Comment by tamasgal** [comment]
Yep, I just ran into this when I dug out some old slides to recycle for a Julia talk.

This should be fixed as soon as possible, it's indeed misleading ;)
