### ISSUE TITLE
Referencing BenchmarkTools.jl from a publication

### ISSUE THREAD

**Issue by angeris** [JuliaCI/BenchmarkTools.jl#137]
Heya! First off, thank you so much for the super useful package!

We were wondering if you had a way to reference this package from a publication—we used it to time the performance of some functions and would love to give credit. We can, at the moment, just write "BenchmarkTools.jl" in the description, but if you had a more specific way of referencing it, that would be great :)

Thanks!

**Comment by vchuravy** [comment]
The right citation afaik is https://arxiv.org/abs/1608.04295

**Comment by angeris** [comment]
Brilliant, thank you, @vchuravy ! Would love to confirm, @jrevels , but this is what I'll be using at the moment!

**Comment by jrevels** [comment]
Yup, that's the one. Thanks for the citation :)

**Comment by angeris** [comment]
Of course! Thanks for the package!

**Comment by angeris** [comment]
Just for completeness, the citing paper can be found [here](https://arxiv.org/pdf/1905.12875). Thank you again for the great package! :)
