### ISSUE TITLE
Test output before benchmark execution

### ISSUE THREAD

**Issue by diegozea** [JuliaCI/BenchmarkTools.jl#14]
Will be great to have a way automatically test the output equality of the outputs at the beginning of the benchmark execution, to avoid regressions in quality during optimization stages.

**Comment by jrevels** [comment]
> test the output equality of the outputs at the beginning of the benchmark execution

I'm not totally sure I understand - what output exists before you execute the benchmark? If you want, you can execute whatever code you'd like in [the `setup` and `teardown` phases](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#setup-and-teardown-phases) of benchmark execution, including [equality testing](https://github.com/JuliaCI/BenchmarkTools.jl/pull/4). Or are you looking for something else?

**Comment by diegozea** [comment]
Thanks! I could add test in the setup phase :)

I was imagine some kind of test and benchmark integration to include the benchmarks in the `test/runtests.jl` file, and having some kind of `Pkg.bench(...)` or `Pkg.test(...,bench=true)` functionality for packages.

**Comment by jrevels** [comment]
I think the kind of functionality you're looking for is now being developed in https://github.com/JuliaCI/PkgBenchmark.jl
