### ISSUE TITLE
Change median and mean export, or update documentation

### ISSUE THREAD

**Issue by milesfrain** [JuliaCI/BenchmarkTools.jl#146]
There's a mismatch between what the documentation suggests and how these functions are exported.

`maximum` and `minimum` are exported to `Base`, while `median` and `mean` are exported to `Statistics`.
https://github.com/JuliaCI/BenchmarkTools.jl/blob/65ef038de1c1ffa0f5d4f4088044214457f0f7df/src/groups.jl#L66-L69

The [manual](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#trial-and-trialestimate) does not mention the need for `using Statistics` to get the the remaining two functions to work.

The [reference guide](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/reference.md#medianxuniontrial-benchmarkgroup) also suggests that `median` and `mean` are exported the same as `minimum` and `maximum`.

Unsure whether `median` and `mean` should be exported to `Base`, since this wouldn't extending an existing `Base` method.

Similar to #143

**Comment by ararslan** [comment]
`median` and `mean` were _removed_ from Base and put into Statistics. We should either reexport those or tell people to run `using Statistics` in the documentation.

**Comment by CameronBieganek** [comment]
I just bumped into this again. I had already forgotten that I needed to do `using Statistics` to get `median` and `mean` to work, and the **BenchmarkTools** documentation didn't remind me...

**Comment by ararslan** [comment]
A PR to document or reexport `mean` and `median` would be welcome. I'm fairly indifferent on which is preferable, though I guess I have a slight inclination toward the latter.

**Comment by milesfrain** [comment]
See #149 for the latter option

**Comment by milesfrain** [comment]
Is there additional documentation required? I thought the fix to re-export now ensures that the existing docs are now aligned with the code.

**Comment by gdalle** [comment]
Maybe just a remark stating that they're re exported is what I had in mind

**Comment by milesfrain** [comment]
Add the remark and applied some additional edits in #336
