### ISSUE TITLE
overhead_sample(evals) and estimate_overhead() gives lower values, the higher "evals" is

### ISSUE THREAD

**Issue by BrucePBon** [JuliaCI/BenchmarkTools.jl#163]
I am evaluating my code and I want to understand why using BenchmarkTools is better than the intuitive and naive process of adding the execution times of your function within a loop with `@time`  and then taking the average value. 

I am looking into BenchmarkTools.jl's code, and I tried running these functions `overhead_sample(evals)` and `estimate_overhead()` because it's a nice idea to measure intrinsic overhead in your machine. However, it turns out `overhead_sample(evals)` returns lower values when one passes higher "evals". 

For evals =    1   -> 6146.
For evals =   10  -> 614.7
for evals =   100 ->  58.67
for evals = 1000 ->  5.867 and so on...

I understand that the code basically measures the time it takes to perform `nothing` "evals" number of times, and then takes the average. But... shouldn't this converge to some number? It seems to get infinitely small as "evals" increases.

**Comment by vchuravy** [comment]
@jrevels Inhttps://github.com/JuliaCI/BenchmarkTools.jl/blob/58262439f18425a35113f12df27821429b07c7d9/src/parameters.jl#L77-L84
Did you intend for the call to `nullfunc` to actually occur? It seems that Julia is now successfully optimizing it out and we would need to use a compiler barrier,
to prevent elision of that loop.
