### ISSUE TITLE
@benchmark/@btime fails with local function

### ISSUE THREAD

**Issue by yha** [JuliaCI/BenchmarkTools.jl#173]
Examples:
```
let x = 1
    f(y) = x+y
    @benchmark f(2)
end # UndefVarError: f not defined

(function (x=1)
    f(y) = x+y
    @benchmark f(2)
end)() # UndefVarError: f not defined
```
(Julia 1.4.2, BenchmarkTools 0.5.0)

**Comment by milankl** [comment]
As I assume this is related,
```julia
julia> for i in 1:20
           @benchmark rand(i)
       end
ERROR: UndefVarError: i not defined
```
same for `@btime`.

**Comment by milankl** [comment]
Ah sorry, interpolation is needed. For both @yha's and my example `$f` and `$i$ solves this issue.

**Comment by ShuhuaGao** [comment]
> Ah sorry, interpolation is needed. For both @yha's and my example `$f` and `$i` solves this issue.

Yes, I also encountered the same issue inside a function. However, if the variable is global, then no interpolation is needed to make the code _run_. Nonetheless, as suggested, it is more accurate to interpolate the variable.
```julia
julia> num = 100
100

julia> @btime sin.(rand(num));
  1.230 μs (5 allocations: 1.81 KiB)

julia> @btime sin.(rand($num));
  957.143 ns (2 allocations: 1.75 KiB)
```

**Comment by KristofferC** [comment]
As been said, you need to interpolate when used in local scope.
