### ISSUE TITLE
Why do execution times get sorted?

### ISSUE THREAD

**Issue by tkralphs** [JuliaCI/BenchmarkTools.jl#179]
It seems the execution times are sorted right before returning the Trials object [here](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/src/execution.jl#L414). I assume there is some rationale for this and it is clearly convenient in many cases. But there are also use cases where you would not want times sorted (e.g., pairwise comparison of results from two different implementations). Since it is easy to sort if needed, but not possible to unsort, an option to get the unsorted list would be really useful. @odow

**Comment by vchuravy** [comment]
I am surprised as well. I don't think there is a consumer that expects them to be sorted, and it feels like this should be a consumer choice.

> pairwise comparison of results from two different implementations

Be careful with that since the reason why we do so many samples is to eliminate noise in the OS/scheduler/CPU.

@jrevels do you recall why we are sorting here? You added it in 77465ba1d81b1df2d3586d6fc64fbfb11feafa2e but that was a while ago ;)

**Comment by tkralphs** [comment]
> Be careful with that since the reason why we do so many samples is to eliminate noise in the OS/scheduler/CPU.

Yeah, I'm aware of the reasons for the sampling and what the pitfalls of pairwise comparison could be. I'm admittedly using/abusing BenchmarkTools for purposes beyond what I think it was originally designed for, but there are cases where pairwise comparison is a reasonable (or at least generally accepted) thing to do. It's not clear that BenchmarkTools is general enough to be the right framework for some things I have in mind, but I'm also just curious to see how its designed and if there's anything I can learn from it, as a relative newbie to Julia.

At the moment, I'm actually using it as a way to illustrate some of the things one should think about in doing rigorous benchmarking for a class I'm teaching. I was looking at a benchmarking script that was using BenchmarkTools and the script was obviously relying on the assumption that the execution times were sorted, which seemed funny to me, so I went poking around and ended up down a rabbit hole. 

For my own purposes, I already forked the project and created a version that doesn't sort, but thought it might be an interesting question to raise. I guess it should be documented one way or the other.

**Comment by jrevels** [comment]
> do you recall why we are sorting here? 

Nope, not really lol. I do remember explicitly taking that out [in my hypothesis testing branch](https://github.com/JuliaCI/BenchmarkTools.jl/issues/74), though, to avoid breaking potential correlation structure

**Comment by tkralphs** [comment]
So should I leave this open? My suggestion would be to add a parameter that is `true` by default so as not to casue problems for anyone already depending on the sorting.

**Comment by vchuravy** [comment]
Happy to take a PR for that.
