### ISSUE TITLE
Invalid redefinition of constant func

### ISSUE THREAD

**Issue by iamed2** [JuliaCI/BenchmarkTools.jl#18]
`func` generated by `@benchmark` conflicts with user variables named `func`.

Example:
```julia
julia> func(x) = x
func (generic function with 1 method)

julia> @benchmark func(3)
ERROR: invalid redefinition of constant func
```

This is on `Julia Version 0.5.0-rc2`

**Comment by jrevels** [comment]
Good catch. `func` (and some other potentially conflicting bindings) are tucked away inside the `let` block [here](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/src/execution.jl#L210).
