### ISSUE TITLE
Behind the scenes of @btime

### ISSUE THREAD

**Issue by SomTambe** [JuliaCI/BenchmarkTools.jl#185]
It's been a few days since I have been testing CUDA.jl. This was one of the basics I tried from the tutorial.
```julia
julia> using CUDA, BenchmarkTools, Test
julia> y=CUDA.fill(2.0f0,2^20)

julia> x=CUDA.fill(1.0f0,2^20)

julia> @test all(Array(x).==1.0f0)
Test Passed

julia> @test all(Array(y).==2.0f0)
Test Passed
```
Then I write a parallel GPU kernel-
```julia
julia> function gpu_par_add!(y,x)
           index=threadIdx().x
           stride=blockDim().x
           for i=index:stride:length(y)
               y[i]+=x[i]
           end
           return nothing
       end
julia> @cuda threads=256 gpu_par_add!(y,x)

julia> @test all(Array(y).==3.0f0)
Test Passed

julia> function bench_par_add!(y,x)
           CUDA.@sync begin
               @cuda threads=256 gpu_par_add!(y,x)
           end
       end
bench_par_add! (generic function with 1 method)
```
Now I try timing the function but then this interesting thing happens-
```julia
julia> @btime bench_par_add!($y,$x)
  1.402 ms (20 allocations: 496 bytes)

julia> @test all(Array(y).==3.0f0)
Test Failed at REPL[21]:1
  Expression: all(Array(y) .== 3.0f0)
ERROR: There was an error during testing

julia> y
1048576-element CuArray{Float32,1}:
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
 5730.0
    ⋮

```
I don't know why I tried testing the value of `y` after the benchmark, but I did not expect it to be anything other than `3.0`. 
Any particular reason why the vector gets such a value? I suppose it has something to do with the mechanism of BenchmarkTools.jl, and I'd like to what lies underneath since I haven't myself explored the codebase (perhaps will do it sometime when I'm free).

**Comment by SomTambe** [comment]
I talked to one of my friends and read a bit about it. Seems like it takes multiple readings which can be seen in the more expanded `@benchmark` macro. I am inferring that 5727 times to have gotten to the value of 5730. I don't think this should happen, instead, it should operate on a copy of the variable passed so that the value of the variable does not change.

I would like to hear what others think about this. A bit of insight from experienced members of the community would be great!

**Comment by vchuravy** [comment]
This is intended and documented behaviour, the behaviour that you want can be achieved with `setup` and `evals=1` see https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#setup-and-teardown-phases

BenchmarkTools always uses the expression provided and doesn't try to infer any further intent. I hope this answers your question.
