### ISSUE TITLE
Printing in 0.5 not working correctly.

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/BenchmarkTools.jl#2]
Maybe you are already aware but in case not, the printing to REPL is a bit wonky on 0.5. 

![image](https://cloud.githubusercontent.com/assets/1282691/15231330/ba20fca6-189a-11e6-9e60-a6f57f71beb0.png)

I am not expecting stuff to work on 0.5 so take this just as a heads up :)

**Comment by jrevels** [comment]
You have to call `show` on them manually in v0.5, since v0.5's REPL calls the compact version by default. I found it really annoying, so I filed an issue in Base [here](https://github.com/JuliaLang/julia/issues/16026).

**Comment by KristofferC** [comment]
Ah thanks!

**Comment by tkelman** [comment]
Reopen? From Jeff's comment that closed that issue, seems some changes need to be made here?

**Comment by jrevels** [comment]
I think I resolved this in #9 (unless something changed on master that I missed).

**Comment by tkelman** [comment]
Ah, my mistake. You should tag a new release.
