### ISSUE TITLE
@benchmark error when try using local variables in 'for' statement (UndefVarError)

### ISSUE THREAD

**Issue by ehgus** [JuliaCI/BenchmarkTools.jl#206]
```julia
julia> for i in 1:5
           @benchmark div(100,i)
       end

ERROR: UndefVarError: i not defined
```

```julia
julia> for i in 1:5
           j = 3
           @benchmark div(100,j)
       end

ERROR: UndefVarError: j not defined
```

**Comment by ederag** [comment]
From the [documentation](https://juliaci.github.io/BenchmarkTools.jl/dev/manual/#Interpolating-values-into-benchmark-expressions),

> Normally, you can't use locally scoped variables in `@benchmark` or `@benchmarkable`, since all benchmarks are defined at the top-level scope by design. However, you can work around this by interpolating local variables into the benchmark expression

In your case:
```julia
for i in 1:5
    @benchmark div(100, $i)
end
```

**Comment by ehgus** [comment]
Ah, sorry. I should read document carefully. Thank you for your kindness!
