### ISSUE TITLE
A more compact, colourful, output style.

### ISSUE THREAD

**Issue by tecosaur** [JuliaCI/BenchmarkTools.jl#215]
Hi!

I find this tool great to use, but I can't help but think that the visual output could be polished a bit. One micro-benchmark tool that I think does a really nice job with this is [hyperfine](https://github.com/sharkdp/hyperfine).

![image](https://user-images.githubusercontent.com/20903656/119652651-f57de480-be58-11eb-8d5d-168ddc581f9c.png)

I think looking at what's done well by it could lead to a Benchmark output that's a bit easier to glance at :slightly_smiling_face: 

For example:

![image](https://user-images.githubusercontent.com/20903656/119679209-c07e8b80-be72-11eb-8696-b2f7d12d2b45.png)

which I think is nicer than

![image](https://user-images.githubusercontent.com/20903656/119674898-2a953180-be6f-11eb-9e59-4cb18f6ee3f3.png)

**Comment by tecosaur** [comment]
If you'd like, I'd be happy to make a PR implementing this :slightly_smiling_face:.

**Comment by tecosaur** [comment]
Oh, another idea I've just had. Instead of a boxplot, one could use the unicode block characters to produce a histogram.

![image](https://user-images.githubusercontent.com/20903656/119680334-ac875980-be73-11eb-88e0-1bf2085c3d55.png)

**Comment by tecosaur** [comment]
So, the above is a mock-up I made by `echo`ing a string + shell-escape colour codes. But I liked the idea enough that I thought I'd code it up for my own beautification if nothing else. This is what I currently have:

![image](https://user-images.githubusercontent.com/20903656/119811926-2eca5900-bf1a-11eb-948b-a7fd377c0bca.png)

**Comment by tecosaur** [comment]
A heuristic to determine if the frequency should be logged would be good I think. Please let me know if you have any good ideas for a check. For reference, the above without logging frequency looks like this:

![image](https://user-images.githubusercontent.com/20903656/119814297-d34d9a80-bf1c-11eb-8163-addc6631ded8.png)

which I think is far less informative.

**Comment by tecosaur** [comment]
> I think it is not correct to override the current @benchmark macro which output is well known and readable.

I must admit I don't quite see your point here. My proposed replacement is perfectly readable, and I don't see the point of "well known" unless the way information is structured takes much getting used to --- and I don't think either the current or my proposed approaches do.

**Comment by Arkoniak** [comment]
My point is that all people are different and some prefer an existing version of `@benchmark` output to your proposal. It is not fair to force this design on them. At the very least, people should have a choice what version they want to use.

**Comment by ptoche** [comment]
IMHO the colors and other refinements should go into another package.
