### ISSUE TITLE
Improve histogram on Windows in default console

### ISSUE THREAD

**Issue by mkitti** [JuliaCI/BenchmarkTools.jl#242]
In the default console that Julia is started with, the histogram does not look too great:

![image](https://user-images.githubusercontent.com/8062771/127766865-58dc4121-8564-4a32-9574-3bfc2dda5a23.png)

It looks much better in [Windows Terminal](https://github.com/microsoft/terminal):

![image](https://user-images.githubusercontent.com/8062771/127766925-17c3449f-f1e2-4aaf-8487-9aec9da25b4e.png)

Could the appearance in the default Windows terminal be improved? Is it possible to not display the histogram? Perhaps we should just wait for Windows Terminal to become the default terminal for Windows or Julia.

**Comment by vchuravy** [comment]
@tecosaur any ideas?

**Comment by tecosaur** [comment]
Hmmm, two things come to mind for me:
1. Optional histogram
2. Ability to change the characters used for the histogram

**Comment by vchuravy** [comment]
Yeah changing the character used for the histogram on windows might be the most prudent? I don't think we can detect the terminal used.

Or we can just say in the docs: Use a decent terminal xD

**Comment by tecosaur** [comment]
This may sound a bit mean, but TBH given that box drawing chars (like used here) were part of the original Unicode 1.0 spec (published 1991) and Julia heavily uses Unicode characters, I'm not sure that we should worry about resolving bad unicode/terminal issues.

**Comment by vchuravy** [comment]
Yeah we recommend as such https://github.com/JuliaLang/julia#terminal-editors-and-ides
