### ISSUE TITLE
Issues with `BenchmarkTools.DEFAULT_PARAMETERS.samples` and `BenchmarkTools.DEFAULT_PARAMETERS.seconds`

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaCI/BenchmarkTools.jl#251]
Have a look at the following code:

```julia
using BenchmarkTools;
using Random;

BenchmarkTools.DEFAULT_PARAMETERS.samples   = 50;
BenchmarkTools.DEFAULT_PARAMETERS.evals     = 1;
BenchmarkTools.DEFAULT_PARAMETERS.seconds   = 15;

vX = rand(5_000);

startTime = time();
sBenchMark = @benchmark sin.(vY) setup = (vY = copy($vX));
runTime = time() - startTime;

display(sBenchMark);

println("\nTotal Run Time $runTime [Sec]\n");
```

On my computer each evaluation takes ~ 35 [Micro Sec].
Yet the run time is ~15 [Sec] even though it should do only 50 evaluations (~1750 Micro Sec).

**Comment by gdalle** [comment]
This is probably because the benchmark is tuned before being run, which actually accounts for the majority of the computation time:

https://juliaci.github.io/BenchmarkTools.jl/stable/reference/#BenchmarkTools.tune!-Tuple{BenchmarkGroup}
