### ISSUE TITLE
How do you save benchmark results?

### ISSUE THREAD

**Issue by FelixBenning** [JuliaCI/BenchmarkTools.jl#289]
https://juliaci.github.io/BenchmarkTools.jl/dev/manual/#Caching-Parameters

1. Start a Julia session
2. Execute a benchmark suite using an old version of your package
3. Save the results somehow (e.g. in a JSON file)

how? The following description is about saving the parameters to a file, but how do I actually save the Benchmark Results?

**Comment by FelixBenning** [comment]
```julia
results = run(suite, verbose = true)

BenchmarkTools.save("output.json", median(results))
```
cf. https://github.com/benchmark-action/github-action-benchmark/blob/master/examples/julia/fib.jl

This seems to work. Now I just need to figure out to load that back in.

**Comment by vandre** [comment]
I found the BenchmarkTools.save method too verbose for my liking. You can also save the benchmark results as follows:

```
using BenchmarkTools
using JSON

t = @benchmark fib(n) samples=10
data = Dict("mean"=> mean(t).time, "min"=> minimum(t).time, 
"max"=> maximum(t).time, "med"=>median(t).time)
open("output.json", "w") do f  JSON.print(f, data) end
```
