### ISSUE TITLE
`@btime` has constant runtime whereas `@time` is dependent on input

### ISSUE THREAD

**Issue by roflmaostc** [JuliaCI/BenchmarkTools.jl#301]
Hi, 

the following example confuses me.

The compiler is able to reduce the function to the constant O(1) [Gauss sum](https://de.wikipedia.org/wiki/Gau%C3%9Fsche_Summenformel). But only when used with `@btime`. With `@time` the runtime is dependent on `N`.

```julia
julia> using BenchmarkTools

julia> function f(N)
                  x = 0
                  for i in 1:N
                      x += i
                  end
                  x
              end
f (generic function with 2 methods)

julia> @time f(10)
  0.000001 seconds
55

julia> @time f(100_000)
  0.000109 seconds
5000050000

julia> @time f(100_000_000)
  0.107553 seconds
5000000050000000

julia> @btime $f(100_000_000)
  2.327 ns (0 allocations: 0 bytes)
5000000050000000

julia> @btime $f(100_000)
  2.328 ns (0 allocations: 0 bytes)
5000050000

julia> @btime $f(10)
  2.327 ns (0 allocations: 0 bytes)
55
```

Why is that?

**Comment by vtjnash** [comment]
`btime` inlines the computation for measuring repeated calls, while `time` records the cost of the call occurring once. Both accurate measurements, but of different operations.

**Comment by vchuravy** [comment]
It take the call `f(10)` and creates a new function `g() = f(10)` and then benchmarks the call to `g`.
Now `N` is known to be constant and the compiler can optimize that.

**Comment by roflmaostc** [comment]
Ah, got it! Thanks @vchuravy @vtjnash !
