### ISSUE TITLE
Add logo?

### ISSUE THREAD

**Issue by gdalle** [JuliaCI/BenchmarkTools.jl#316]
@cormullion had a logo suggestion for BenchmarkTools.jl which I kinda like

https://github.com/JuliaLang/www.julialang.org/issues/818#issuecomment-629851911

thoughts?

**Comment by gdalle** [comment]
![juliaperformance](https://github.com/JuliaCI/BenchmarkTools.jl/assets/22795598/beba74b7-9a47-4ad5-b9bc-b4f013452df0)

Done with the following code:

```julia
using Luxor

JULIA_COLORS = [Luxor.julia_blue, Luxor.julia_green, Luxor.julia_red, Luxor.julia_purple]

function main()
    Drawing(500, 500, "/tmp/juliaperformance.svg")
    origin()
    squircle(O, 250, 250, :clip, rt=0.3)
    sethue("white")
    paint()

    @layer begin
        translate(0, 200)
        rmin = 150
        rmax = 260
        band = 40

        for n in 1:4
            setblend(blend(O - (240, 0), O + (240, 0), "white", JULIA_COLORS[n]))
            sector(O,
                rescale(n, 1, 3, rmin, rmax),
                rescale(n, 1, 3, rmin, rmax) + band,
                3π / 2 - deg2rad(45), 3π / 2 + deg2rad(45),
                :fill)
        end

        sethue("white")
        setline(25)
        line(O, polar(400, deg2rad(290)), :strokepreserve)
        setline(14)
        sethue("black")
        strokepath()
        circle(O, 30, :fill)
    end

    finish()
    preview()
end

main()
```

**Comment by cormullion** [comment]
Nice job. A version in black could look cool:

![juliaperformance-black](https://github.com/JuliaCI/BenchmarkTools.jl/assets/52289/0215e704-7641-4cec-8f34-a81a8bd2707b)

**Comment by ararslan** [comment]
Love it! Where are you thinking the logo should go? The repository settings allow you to provide an image as a "social media preview" but I have no idea what that actually means. We could add it to the README.

**Comment by cormullion** [comment]
The "social  media preview" is the image you get when people link to your site on those social media sites I hear so much about (do people still use Twitter?😱😀), usually a biggish rectangular image.... if there isn't one in settings you get eg 

<img width="300" alt="Screenshot 2023-06-14 at 17 59 04 copy" src="https://github.com/JuliaCI/BenchmarkTools.jl/assets/52289/9c4f4631-5a53-4e03-9194-9653a47ef8a3">

You'd probably need to make something bigger than a logo (eg https://github.com/cormullion/Karnak.jl ) 

Sometimes there's a place for icon + link: eg on the Julia home page:

<img width="696" alt="Screenshot 2023-06-14 at 18 00 50" src="https://github.com/JuliaCI/BenchmarkTools.jl/assets/52289/f1e1f452-4025-4cc5-afca-1742a37eebb6">

Then there's the Documenter documentation - which has options to show and switch between light and dark mode logos.

**Comment by cormullion** [comment]
You can:

https://github.com/JuliaLang/julia/pull/49544

- especially if Kristoffer approves of it 😛

**Comment by gdalle** [comment]
I don't have access to the repo settings for the social media preview. @vchuravy gimme the power?

**Comment by gdalle** [comment]
Does anyone know why the Readme logo fails to show up?

**Comment by cormullion** [comment]
line 1 of readme doesn’t look like HTML code?

**Comment by ararslan** [comment]
I can add the social media preview. Looks like the images here are square but the section in the settings says:

> Images should be at least 640×320px (1280×640px for best display).

Indeed, putting the square one in there crops the height to fill the width. Does someone want to make a wide version?

**Comment by cormullion** [comment]
![benchmarks-social-media-preview](https://github.com/JuliaCI/BenchmarkTools.jl/assets/52289/db283cab-b871-490f-983e-3aa64cf29124)

**Comment by gdalle** [comment]
You gave in to temptation

**Comment by ararslan** [comment]
Apologies for the delay. The fruit of @cormullion's temptation has been set as the social media preview. What's left to consider this issue complete? Adding the logo to the Documenter styling?

**Comment by gdalle** [comment]
The logo is already in the docs so we can probably close. I'm still a bit confused as to what "Benchmarks.jl" stands for in the social media preview though, isn't it a little misleading regarding the actual name of the package?

**Comment by cormullion** [comment]
Oops - I completely overlooked that mistake ... 😱 I'll redo it tomorrow if that's OK...

**Comment by gdalle** [comment]
@cormullion, casually renaming core packages since 2023

**Comment by cormullion** [comment]
haha - well it really should be Benchmarks, but it superseded an older package with that name already taken, hence the Tools. The rich texture of history ... 😀

**Comment by gdalle** [comment]
Honestly that's half of the reason why I work so hard to make Graphs.jl succeed, it's cause we finally have the right name 🤣

**Comment by cormullion** [comment]
I hope to not see GraphsNext.jl ...

**Comment by gdalle** [comment]
> I hope to not see GraphsNext.jl ...

You just gave me nightmares.

But if all goes well you may not even need to see MetaGraphs(Next).jl ever again

**Comment by cormullion** [comment]
![benchmarks-social-media-preview](https://github.com/JuliaCI/BenchmarkTools.jl/assets/52289/b0195a74-f2e4-4720-b4db-5f5cd860e90c)

**Comment by gdalle** [comment]
@ararslan here we go ^^

**Comment by ararslan** [comment]
Alright, replaced with the updated one 👍
