### ISSUE TITLE
Removing  `leaves` export

### ISSUE THREAD

**Issue by theogf** [JuliaCI/BenchmarkTools.jl#332]
It is currently quite inconvenient that `BenchmarkTools.jl` export the `leaves` function as it is a very common name and tend to clash with a lot of other packages containing Trees.

Would you consider a (breaking) PR which would remove this specific export?

**Comment by gdalle** [comment]
We're heading towards a 2.0 release so it's now or never. Can you maybe check the history of the repo to see whether they list good reasons for the export?

**Comment by theogf** [comment]
I could not find any discussion on it (PR or issues). It has a very clear use (iteration of a `BenchmarkGroup`), I guess the name clash was just never really considered.

Another option would be to depend on `AbstractTrees.jl` but that's a very unnecessary dependency.

**Comment by gdalle** [comment]
Wanna make a PR? Should be a quick review

**Comment by lucaferranti** [comment]
Can open one tomorrow morning if nobody ninjas me by then :)
