### ISSUE TITLE
Tag non-breaking release of BenchmarkTools.jl?

### ISSUE THREAD

**Issue by gdalle** [JuliaCI/BenchmarkTools.jl#344]
Since the last release, there have been 3 commits that I deem possibly breaking:

- https://github.com/JuliaCI/BenchmarkTools.jl/pull/309 => makes it easier to overwrite existing benchmark groups without noticing, but arguably this is a bad practice anyway
- https://github.com/JuliaCI/BenchmarkTools.jl/pull/318 => more likely a bugfix
- https://github.com/JuliaCI/BenchmarkTools.jl/pull/333 => removes an [undocumented](https://github.com/JuliaCI/BenchmarkTools.jl/issues/332#issuecomment-1725672694) export so probably ok

In my view, semantic versioning is slightly looser when it comes to dev-facing packages like BenchmarkTools.jl, and so we could tag a non-breaking release. What do other people think?

**Comment by gdalle** [comment]
PS: I tried to maintain this package for a while but I clearly don't have the bandwidth, so once I get those changes release I'll step aside for a good long while

**Comment by KristofferC** [comment]
> removes an https://github.com/JuliaCI/BenchmarkTools.jl/issues/332#issuecomment-1725672694 export so probably ok

Looking at https://juliahub.com/ui/Search?q=leaves&type=symbols&u=use I don't see any use of (the relevant) `leaves` without explicitly using BenchmarkTools prefix.

**Comment by gdalle** [comment]
then I propose we release 1.4.0
