### ISSUE TITLE
`judge` lacks a docstring

### ISSUE THREAD

**Issue by adienes** [JuliaCI/BenchmarkTools.jl#356]
it's documented in the `Manual` portion of the docs, but considering this is one of the primary exported functions, it should probably also be present in the `Reference` section with a docstring

**Comment by willow-ahrens** [comment]
If you write a PR I'll happily review it!

**Comment by willow-ahrens** [comment]
fixed in https://github.com/JuliaCI/BenchmarkTools.jl/pull/378
