### ISSUE TITLE
Display plot when possible (JuPyteR, Juno (when ready))

### ISSUE THREAD

**Issue by alanedelman** [JuliaCI/BenchmarkTools.jl#36]
I really want a histogram to appear by default
ok to label minimum , maximum, mean

A picture is worth a mega-byte of numbers  :-)

**Comment by jrevels** [comment]
It'd be nice to have some plotting functionality, though it really shouldn't happen by default, and BenchmarkTools shouldn't have a hard dependency on a plotting stack.

BenchmarkTools actually [already has some simple KDE plotting code sitting in the source tree](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/src/plotting.jl), but I didn't expose an API to it and it's not very fleshed out. 

I think the more valuable (but more time/effort-intensive) pursuit would be generating interactive reports as described in #1.
