### ISSUE TITLE
Benchmark results not printed on JUNO/Atom

### ISSUE THREAD

**Issue by Datseris** [JuliaCI/BenchmarkTools.jl#45]
![benchnotshown](https://cloud.githubusercontent.com/assets/19669089/23026792/aa5e66a6-f462-11e6-8ed9-8b6a25220967.PNG)

A method for `render()` has to be defined, as stated by @ChrisRackauckas . 

At the moment the only way to "see" the results in Atom is to press "Copy" in the console and then paste somewhere else :(

(`print()` also doesn't work)

**Comment by ChrisRackauckas** [comment]
For clarity, `Juno.render`. Otherwise it just shows the basic print, and hides the other data. (Juno.jl is a low dependency library for interacting with Juno)

@pfitzseb might be the one to help with this?

**Comment by jrevels** [comment]
Is there a way to resolve this issue without bringing in Juno as a dependency? As @andreasnoack stated in https://github.com/JuliaStats/DataFrames.jl/pull/1164#issue-207852387, it's a hefty dependency to carry around just for pretty printing.

**Comment by ohadle** [comment]
This now works for me ([discussion](https://discourse.julialang.org/t/benchmarktools-jl-and-juno/849/12)).

**Comment by Datseris** [comment]
me too. Turns out the problem was related with Juno and not with BenchmarkTools, I think this can be safely closed.
