### ISSUE TITLE
Pkg.update() didn't update BenchmarkTools, installed for PolyBench

### ISSUE THREAD

**Issue by singam-sanjay** [JuliaCI/BenchmarkTools.jl#62]
I've using PolyBench.jl, which installs BenchmarkTools.jl as a dependency.

I issued Pkg.update() to include the v0.7 deprecation patch, but that didn't update BenchmarkTools. Pkg.update worked only after BenchmarkTools.jl was swtiched to the master branch from a branch that had the same name of it latest commit.

Other packages, including BinDeps, were not on their master branch yet got updated.

Is there an issue with the way I'm using Pkg.update() ?

**Comment by pkofod** [comment]
Would be helpful with a version info output and `Pkg.status()`

**Comment by denius** [comment]
You can manually checkout to latest version by `Pkg.checkout("BenchmarkTools", pull=true)` command, but `BenchmarkTools` is broken on v0.7-DEV
```julia
julia> @btime a=1
ERROR: syntax: invalid syntax (escape (= a 1))
Stacktrace:
 [1] generate_benchmark_definition(::Module, ::Array{Symbol,1}, ::Array{Any,1}, ::Expr, ::Void, ::Void, ::BenchmarkTools.Parameters) at /home/denis/.julia/v0.7/BenchmarkTools/src/execution.jl:289
```
or may be v0.7.0-DEV too crude.

**Comment by jrevels** [comment]
I'm not sure if this was ever a BenchmarkTools issue or a Pkg issue, but at least BenchmarkTools should work on v0.7 now...

**Comment by denius** [comment]
Thanks. Yes, with the latest updates of Julia and BenchmarkTools it's worked on v0.7, I noticed yesterday.
