### ISSUE TITLE
judge working with memory

### ISSUE THREAD

**Issue by mschauer** [JuliaCI/BenchmarkTools.jl#70]
I hope this is isn't a usage question but I think it would be nice if

```julia
julia> judge(memory(oldresults["solver"]), memory(results["solver"]))
ERROR: MethodError: no method matching judge(::Int64, ::Int64)
```
would work

**Comment by gdalle** [comment]
Doing some maintenance around these parts, can you explain why `judge(::Int, ::Int)` is expected to work?

**Comment by mschauer** [comment]
@mschauer from 2017, are you reading this?

**Comment by gdalle** [comment]
Sorry, just doing a bit of cleanup on the repo to see if the old issues are still relevant or not ^^
