### ISSUE TITLE
change name to Benchmarking.jl?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaCI/BenchmarkTools.jl#76]
BenchmarkTools is the bomb and everyone uses it – or should! The name is a little awkward though and doesn't have quite the gravitas and officialness that it deserves. What about calling the package `Benchmarking.jl` so that one writes the lovely definitive sounding `using Benchmarking` when one uses it?

**Comment by musm** [comment]
Another suggestion might be `Benchmarks` (Benchmarks.jl has now been  deprecated for some time, which frees up the name)

**Comment by StefanKarpinski** [comment]
"Benchmarks" sounds like a collection of benchmarks to me.

**Comment by jrevels** [comment]
`TheVeryBestOneTrueBenchmarkPackage.jl`? 😛 

`Benchmarking.jl` sounds fine to me, but not sure if it's worth the churn. What's the package renaming process like? Just rename everything here and register as a new package in METADATA?

**Comment by StefanKarpinski** [comment]
> Just rename everything here and register as a new package in METADATA

No, just change the name here and in METADATA.

**Comment by gdalle** [comment]
Six years on, I think this is such a central package that a name change would be majorly disruptive
