### ISSUE TITLE
Benchmark with @benchmark only one sample?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaCI/BenchmarkTools.jl#89]
I run the following: @benchmark  `heat_juafem_examples.allrun()`

I can see that the macro executes the function  inside the module  `heat_juafem_examples` four times, but  reference to only a single sample is printed:

```
julia> include("heat_juafem_examples.jl"); @benchmark heat_juafem_examples.allrun()
WARNING: replacing module heat_juafem_examples
# heat_juafem_example
# heat_juafem_example
# heat_juafem_example
# heat_juafem_example
BenchmarkTools.Trial:
  memory estimate:  3.65 GiB
  allocs estimate:  20007018
  --------------
  minimum time:     9.877 s (12.50% GC)
  median time:      9.877 s (12.50% GC)
  mean time:        9.877 s (12.50% GC)
  maximum time:     9.877 s (12.50% GC)
  --------------
  samples:          1
  evals/sample:     1

julia> 
```
Am I missing something? Is this the expected behavior?

**Comment by jrevels** [comment]
It is. Before running the actual performance experiment, BenchmarkTools runs a "tuning" process in which the provided kernel is executed several times in order to gauge how many kernel evaluations per sample is needed to minimize error due to timer precision/accuracy. 

See https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#introduction

**Comment by PetrKryslUCSD** [comment]
Would you please keep this discussion open for a while?

I don't think it is reasonable for the benchmark  to conclude that only a single sample is sufficient. Clearly even when the tuning decides  that the execution time for one sample is reasonably long,  there is still scatter. In the referenced example, the scatterer is actually between  something like  9.6 and 10.1 over five runs. In my opinion that is significant.

**Comment by jrevels** [comment]
> Would you please keep this discussion open for a while?

People can still comment on a closed issue, so feel free to discuss. But this is intended behavior, so there's no action item, and hence I closed the issue.

> I don't think it is reasonable for the benchmark to conclude that only a single sample is sufficient.

BenchmarkTools doesn't ever make any statistical decisions about how many samples to take. It takes at least one sample, and then as many additional samples as possible [within the user-provided time and sample budget.](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#benchmark-parameters) As described in the docs, the default time budget is 5 seconds, so BenchmarkTools took as many samples as it could (which, of course, is only one).

**Comment by PetrKryslUCSD** [comment]
I see. I missed the part about being able to control the number of samples. Thanks a bunch.
