### ISSUE TITLE
Benchmarking across a range of inputs

### ISSUE THREAD

**Issue by vchuravy** [JuliaCI/BenchmarkTools.jl#91]
One of the features I really like from [google/benchmark](https://github.com/google/benchmark) is the ability to benchmark across a range of input values.
Since the size of the data can have impacts on performance due to cache behaviour, I often find myself benchmarking with different arraysizes.

**Comment by jrevels** [comment]
(Valentin and I discussed this offline, posting the conclusion here for public history's sake)

Assuming you mean something like

```julia
for i in i_iterator, j in j_iterator
    @benchmark(kernel(x), setup = (x = f(i, j))
end
```

...then I imagine this issue is requesting an interface like

```julia
@benchmark(kernel(x), range = (i = i_iterator, j = j_iterator), setup = (x = f(i, j)))
```

...but IMO it's nicer/more Julian to just to use generators/map/etc., e.g.

```julia
collect(@benchmark(kernel(x), setup = (x = f(i, j))) for i in i_iterator, j in j_iterator)
```
